// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5WVvHqOEIEIWQk109i31pBR7tBZ-LNeI',
    appId: '1:975591717833:web:c65bec1053357cf5e9c618',
    messagingSenderId: '975591717833',
    projectId: 'data-aa820',
    authDomain: 'data-aa820.firebaseapp.com',
    databaseURL: 'https://data-aa820-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'data-aa820.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByK7JEr9-tqv_wYUKRAn5SOyArmywLC9g',
    appId: '1:975591717833:android:244d153eba5eaabae9c618',
    messagingSenderId: '975591717833',
    projectId: 'data-aa820',
    databaseURL: 'https://data-aa820-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'data-aa820.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp3LyWVKh1UcMouW7AjC0Emaz8A5lJwEU',
    appId: '1:975591717833:ios:3f9eff4ed3c72e5be9c618',
    messagingSenderId: '975591717833',
    projectId: 'data-aa820',
    databaseURL: 'https://data-aa820-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'data-aa820.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp3LyWVKh1UcMouW7AjC0Emaz8A5lJwEU',
    appId: '1:975591717833:ios:3f9eff4ed3c72e5be9c618',
    messagingSenderId: '975591717833',
    projectId: 'data-aa820',
    databaseURL: 'https://data-aa820-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'data-aa820.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5WVvHqOEIEIWQk109i31pBR7tBZ-LNeI',
    appId: '1:975591717833:web:76b7e81db1d34d8fe9c618',
    messagingSenderId: '975591717833',
    projectId: 'data-aa820',
    authDomain: 'data-aa820.firebaseapp.com',
    databaseURL: 'https://data-aa820-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'data-aa820.firebasestorage.app',
  );

}